name: CHOCOLATINE Workflow

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  TARGET_REPO: ${{ secrets.MIRROR_URL }}
  EXEC_NAME: 'chocolatine_exe'

jobs:
  style_check:
    name: Validate Coding Style
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - name: Sync Code
        uses: actions/checkout@v3

      - name: Coding Style Evaluation
        run: |
          check_style.sh $(pwd) $(pwd)
          if [ -s style-errors.log ]; then
            echo "Found style issues:"
            cat style-errors.log
            exit 1
          fi

  compile_program:
    name: Compile Chocolatine
    needs: style_check
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/compile-env:latest

    steps:
      - name: Sync Code
        uses: actions/checkout@v3

      - name: Compilation
        run: |
          make
          make clean

      - name: Validate Executable
        run: |
          if [ ! -x "${EXEC_NAME}" ]; then
            echo "${EXEC_NAME} is not executable or missing."
            exit 1
          fi

  testing:
    name: Execute Tests
    needs: compile_program
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/test-env:latest

    steps:
      - name: Sync Code
        uses: actions/checkout@v3

      - name: Run Chocolatine Tests
        run: make tests_run

  mirror_repo:
    name: Mirror to Target Repository
    needs: testing
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.TARGET_REPO }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
